#!/usr/bin/env bash

# https://github.com/adi1090x/polybar-themes
# https://github.com/adi1090x/rofi

THEME=$1

dir="$HOME/.config/rofi/launchers/text"
styles=($(ls -p --hide="colors.rasi" $dir/styles))
color="${styles[$(( $RANDOM % 10 ))]}"

rofi -no-lazy-grab -show drun \
-modi run,drun,window \
-theme $THEME

